# MarketEdge System Status & Uptime Monitoring
owner: GRAFFITI-LLC
repo: me-status

sites:
  - name: MarketEdge Production (Web)
    url: https://www.mktedg.com
    expectedStatusCodes:
      - 200
      - 301
      - 302
    maxResponseTime: 5000

  - name: MarketEdge API Health
    url: https://www.mktedg.com/api/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: MarketEdge GraphQL Endpoint
    url: https://www.mktedg.com/api/graphql
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"query": "{ __typename }"}'
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

status-website:
  # GitHub Pages default URL (カスタムドメインは後で設定)
  baseUrl: /me-status
  name: MarketEdge Status
  introTitle: "**MarketEdge** システムステータス"
  introMessage: リアルタイムでMarketEdgeの稼働状況を確認できます
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Main Site
      href: https://www.mktedg.com

# Slack notifications
notifications:
  - type: slack
    webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}

# Assignees for issues
assignees:
  - ttorii20

# Commit messages
commitMessages:
  readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
  summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
  graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"

user-agent: upptime/marketedge